import = [
	"~/.config/alacritty/themes/themes/zenburn.toml"
]

[font]
size = 8.0

[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"
